# Get editor completions based on the config schema
"$schema"='https://starship.rs/config-schema.json'

format="""
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$docker_context\
$package\
$c\
$cmake\
$guix_shell\
$helm\
$opa\
$pulumi\
$rust\
$terraform\
$typst\
$nix_shell\
$memory_usage\
$direnv\
$env_var\
$custom\
$kubernetes\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$os\
$container\
$netns\
$shell\
$character"""

[git_commit]
only_detached=false
style='8'

[git_status]
stashed=''

[kubernetes]
disabled=false
format='[\($context/$namespace\) ]($style)'
style='green bold'

[shell]
disabled=false

[shlvl]
disabled=false
symbol=''
