# Get editor completions based on the config schema
"$schema"='https://starship.rs/config-schema.json'

format="""
$shell\
$kubernetes\
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$docker_context\
$package\
$c\
$cmake\
$guix_shell\
$helm\
$opa\
$pulumi\
$rust\
$terraform\
$typst\
$nix_shell\
$memory_usage\
$direnv\
$env_var\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$os\
$container\
$netns\
$character"""

[character]
error_symbol = '[\$](bold 8)'
success_symbol = '[\$](bold 8)'

[[battery.display]]
threshold = 30

[directory]
format='\[[$path]($style)[$read_only]($read_only_style)\] '
repo_root_style='bold cyan underline'
fish_style_pwd_dir_length=2

[git_branch]
format = '\[[$symbol$branch]($style)\] '

[git_commit]
only_detached=false
style='8'

[git_status]
stashed=''
format = '([\[$all_status$ahead_behind\]]($style)) '

[kubernetes]
detect_env_vars=[
  "KUBECONFIG",
]
disabled=false
format='\[[$symbol$context:$namespace]($style)\] '
style='green bold'

[shell]
disabled=false

[shlvl]
disabled=false
symbol=''

[status]
disabled=false
format='[$symbol $status]($style) '
pipestatus=true

##########################     Bracketed segments     ##########################

[c]
format = '\[[$symbol($version(-$name))]($style)\] '

[cmake]
format = '\[[$symbol($version)]($style)\] '

[docker_context]
format = '\[[$symbol$context]($style)\] '

[helm]
format = '\[[$symbol($version)]($style)\] '

[hostname]
format = '\[[$ssh_symbol$hostname]($style)\] '

[memory_usage]
format = '\[$symbol[$ram( | $swap)]($style)\] '

[opa]
format = '\[[$symbol($version)]($style)\] '

[os]
format = '\[[$symbol]($style)\] '

[package]
format = '\[[$symbol$version]($style)\] '

[rust]
format = '\[[$symbol($version)]($style)\] '

[sudo]
format = '\[[as $symbol]($style)\] '

[terraform]
format = '\[[$symbol$workspace]($style)\] '

[time]
format = '\[[$time]($style)\] '

[username]
format = '\[[$user]($style)\] '
