# yamllint disable rule:line-length
# Use like this:
# helm install www oci://registry-1.docker.io/bitnamicharts/nginx --version 18.2.3 -f ~/res/kubernetes/bitnami-nginx-values.yaml
---
ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hostname: foobar.example.com
  tls: true
service:
  type: ClusterIP
tls:
  enabled: false
