---
# Pod to help with debugging
apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/description: >
      A pod to debug things.
  name: hack
  labels:
    app.kubernetes.io/name: hack
    app.kubernetes.io/created-by: "Andreas"
spec:
  containers:
    - name: hack
      image: ubuntu
      command:
        - sleep
        - "3600"
      imagePullPolicy: Always
      # securityContext:
      #   allowPrivilegeEscalation: false
      #   capabilities:
      #     drop:
      #       - ALL
      #   runAsNonRoot: true
      #   runAsUser: 1000
      #   runAsGroup: 1000
      #   seccompProfile:
      #     type: RuntimeDefault
      # volumeMounts:
      #   - name: storage-volume
      #     mountPath: /mnt
  restartPolicy: Never
  terminationGracePeriodSeconds: 0
  # volumes:
  #   - name: storage-volume
  #     persistentVolumeClaim:
  #       claimName: example-pvc
