---
# Pod to help with debugging
apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/description: >
      A pod to debug things.
  name: hack
  labels:
    app.kubernetes.io/name: hack
    app.kubernetes.io/created-by: "Andreas"
spec:
  containers:
    - name: hack
      image: ubuntu
      command:
        - sleep
        - "3600"
      imagePullPolicy: Always
  restartPolicy: Never
  terminationGracePeriodSeconds: 0
