# Pod to help with debugging
apiVersion: v1
kind: Pod
metadata:
  name: hack
  labels:
    app.kubernetes.io/name: hack
    app.kubernetes.io/created-by: "Andreas"
spec:
  containers:
  - name: hack
    image: alpine
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Never

