---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: example
spec:
  # yamllint disable-line rule:line-length
  volumeSnapshotClassName: trident  # Replace with your volume snapshot class name
  source:
    persistentVolumeClaimName: example-pvc  # Replace with your PVC name
