---
name: Lint and checks
run-name: Linting ${{ github.sha }}
on:  # yamllint disable-line rule:truthy
  - push
  - pull_request
jobs:
  ShellCheck:
    runs-on: ubuntu-latest
    steps:
      - name: Check out ${{ github.repository }}:${{ github.ref_name }}
        uses: actions/checkout@v3
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@2.0.0
        with:
          ignore_names: >-
            .zsh*
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out ${{ github.repository }}:${{ github.ref_name }}
        uses: actions/checkout@v3
      - name: Run yamllint
        run: |
          yamllint .
